name: Bug report
description: Create a report to help us fix something that is broken
labels: ["Bug"]

body:
  - type: markdown
    attributes:
      value: |
        This is a template to help you report good issues. You may use [Github Markdown](https://help.github.com/articles/getting-started-with-writing-and-formatting-on-github/) syntax to format your issue report.
        
  - type: textarea
    id: bug
    attributes:
      label: Bug
      description: Please give a short description of the bug
    validations:
      required: true

  - type: input
    id: environmentversion
    attributes:
      label: Environment Version
      description: Affected Dolibarr version(s)

  - type: input
    id: environmentos
    attributes:
      label: Environment OS
      description: Server OS type and version
      
  - type: input
    id: environmentwebserver
    attributes:
      label: Environment Web server
      description: Webserver type and version
      
  - type: input
    id: environmentphp
    attributes:
      label: Environment PHP
      description: PHP version
      
  - type: input
    id: environmentdatabase
    attributes:
      label: Environment Database
      description: Database type and version

  - type: input
    id: environmenturls
    attributes:
      label: Environment URL(s)
      description: Affected URL(s)

  - type: textarea
    id: expectedbehaviour
    attributes:
      label: Expected and actual behavior
      description: Verbose description

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the behavior
      description: Verbose description
      
  - type: textarea
    id: files
    attributes:
      label: Attached files
      description: Screenshots, screencasts, dolibarr.log, debugging informations
      
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Dolibarr/dolibarr/blob/develop/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
