name: GitHub CI PHPCS and PHPCBF

on: push
#on: 
#  push:
#    paths:
#    - '**.php'

jobs:
  filesChanged:
    uses: ./.github/workflows/files_changed.yaml
    with:
      folder_path: .*
      
  linter_name:
    name: Run & fix PHP Code Sniffer
    runs-on: ubuntu-latest
    needs: filesChanged
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10
      - name: echo Get list of all changed files
        run: |
          echo ${{ needs.filesChanged.outputs.all_changed_files }} 
          echo boolean_output=${{ needs.filesChanged.outputs.boolean_output }} 
      - uses: eldy/phpcsfixer-action@master
        with:
          github_token: ${{ secrets.github_token }}
          use_default_configuration_file: false
          phpcs_standard: 'dev/setup/codesniffer/ruleset.xml'
      #- uses: stefanzweifel/git-auto-commit-action@v4 # auto commit the fixes action for GitHub
      #  with:
      #    commit_message: Fix PHPCS errors
