name: GitHub CI PHPCS and PHPCBF

on: push

jobs:
  linter_name:
    name: Run & fix PHP Code Sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shalior/wordpress-phpcs-action@master
        with:
          github_token: ${{ secrets.github_token }}
          use_default_configuration_file: false
          phpcs_standard: 'dev/setup/codesniffer/ruleset.xml'
          #phpcs_args: '-n -s --extensions=php --colors --tab-width=4 --encoding=utf-8 --runtime-set ignore_warnings_on_exit true'
          phpcs_args: '-n .'
      #- uses: stefanzweifel/git-auto-commit-action@v4 # auto commit the fixes action for GitHub
      #  with:
      #    commit_message: Fix PHPCS errors
